version: 2.1

orbs:
  slack: circleci/slack@5.1.1

jobs:
  performance-budget-check:
    machine: true 
    steps:
      - checkout 

      - run:
          name: Run Sitespeed.io against deployed site
          command: |
            docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:37.9.0 \
              https://landing-page-iota-virid.vercel.app/ \
              --budget.configPath /sitespeed.io/budget.json

      - store_artifacts:
          path: sitespeed-result
          destination: sitespeed-report

workflows:
  version: 2.1
  enforce-performance-budget:
    jobs:
      - performance-budget-check:
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1

        