version: 2.1

jobs:
  performance-budget-check:
    machine: true  # Use full Linux VM with native Docker access
    working_directory: ~/repo  # Set working directory for clarity
    steps:
      - checkout  # Clone your GitHub repo into the VM

      - run:
          name: Confirm budget.json is present
          command: |
            ls -lah
            cat budget.json

      - run:
          name: Run Sitespeed.io against deployed site
          command: |
            docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:37.9.0 \
              https://landing-page-iota-virid.vercel.app/ \
              --budget.configPath /sitespeed.io/budget.json

      - store_artifacts:
          path: sitespeed-result
          destination: sitespeed-report

workflows:
  version: 2.1
  enforce-performance-budget:
    jobs:
      - performance-budget-check
